### ISSUE TITLE
Middle white Line at First Date and Last Date

### ISSUE THREAD

**Issue by naufalmms** [savvisingh/DateRangePicker#39]
![photo_2018-08-20_11-50-16](https://user-images.githubusercontent.com/32739956/44320987-8be27780-a46f-11e8-8f96-cd8f23a26d12.jpg)

can you tell me why at this library have white line at first date and lastdate selected

**Comment by pandelisgreen13** [comment]
The problem is in the next drawables:
state_range_first
state_range_last
state_range_middle

The problem is with the android:strokeColor, it is transparent.
At sometimes it is shown and we see these white lines

`<vector xmlns:android="http://schemas.android.com/apk/res/android"
  android:width="24dp"
  android:height="24dp"
  android:viewportHeight="48.0"
  android:viewportWidth="48.0">
  <path
    android:fillColor="#0E67B1"
    android:pathData="M24,8h24v32h-24z"
    android:strokeColor="#00000000"
    android:strokeWidth="1" />
  <path
    android:fillColor="#0E67B1"
    android:pathData="M 24,8 C 0,8 0,40 24,40z "
    android:strokeColor="#**00000000**"
    android:strokeWidth="1" />
</vector>
`
